repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        args:
        - --diff
        - --check
-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear==20.11.1]
        args:
        - --ignore=E203,B305,B950,E402,E501,E722,F401,W503
        - --select=C,E,F,W,B,B9
        - --max-line-length=88

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    -   id: mypy
        additional_dependencies: [sqlalchemy-stubs==0.4]
        args:
        - --allow-redefinition
